version: '3.8'

services:
  redis1:
    image: redis:latest
    container_name: redlock-redis1
    ports:
      - "7000:6379"
    command: redis-server --save "" --appendonly no

  redis2:
    image: redis:latest
    container_name: redlock-redis2
    ports:
      - "7001:6379"
    command: redis-server --save "" --appendonly no

  redis3:
    image: redis:latest
    container_name: redlock-redis3
    ports:
      - "7002:6379"
    command: redis-server --save "" --appendonly no